apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: primary-backend-monitor
spec:
  selector:
    matchLabels:
      app: primary-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
